
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');

/**
 * Christian Culture PWA Service Worker - CC RADIO v4.6.075
 */

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);
cleanupOutdatedCaches();

// Custom logic for audio streams - bypass SW completely and never cache live streams
registerRoute(
  ({ request, url }) => 
    request.destination === 'audio' || 
    request.destination === 'video' ||
    url.hostname.includes('zeno.fm') ||
    url.pathname.includes('.m3u8') ||
    url.pathname.includes('.ts') ||
    url.pathname.includes('stream'),
  new NetworkOnly()
);

// Ensure version.json is always fresh
registerRoute(
  ({ url }) => url.pathname.endsWith('version.json'),
  new NetworkOnly()
);

// Standard navigation route
try {
  registerRoute(
    new NavigationRoute(createHandlerBoundToURL('/index.html'))
  );
} catch (e) {
  // Fallback
  registerRoute(
    new NavigationRoute(async () => {
      const resp = await caches.match('/index.html', { ignoreSearch: true });
      return resp || fetch('/index.html');
    })
  );
}

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data && event.data.type === 'GET_VERSION') {
    // Respond to the client with the version baked into this service worker build
    event.source.postMessage({
      type: 'VERSION_INFO',
      version: self.__APP_VERSION__ || "26.5.17.1"
    });
  }
  if (event.data && event.data.type === 'UPDATE_NOTIFICATION_SETTINGS') {
    // Store settings in IndexedDB or similar if needed for SW logic
    console.log('[SW] Notification settings updated:', event.data.settings);
  }
  if (event.data && event.data.type === 'SYNC_OFFLINE_CONTENT') {
    console.log('[SW] Syncing offline content (Bible) requested...');
    event.waitUntil((async () => {
      try {
        const cache = await caches.open('cc-core-content-v1');
        await cache.add('/bible.json');
        console.log('[SW] bible.json cached successfully for offline use.');
      } catch (e) {
        console.error('[SW] Failed to cache offline content:', e);
      }
    })());
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Periodic Sync for "Moment of Peace" notifications
self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'moment-of-peace') {
    event.waitUntil(showMomentOfPeaceNotification());
  }
});

async function showMomentOfPeaceNotification() {
  const titles = [
    "Chwila Pokoju", 
    "Zatrzymaj się na moment", 
    "Duchowy Oddech",
    "Moment z Jahwe"
  ];
  const messages = [
    "Zatrzymaj się na 30 sekund i podziękuj za dzisiejszy poranek.",
    "Pomyśl o jednej osobie, której możesz dziś wybaczyć.",
    "Bóg jest z Tobą w tej właśnie chwili. Uśmiechnij się.",
    "Oddaj Jahwe swoje troski na najbliższą godzinę.",
    "Pamiętaj: Jesteś ukochanym dzieckiem Boga."
  ];

  const title = titles[Math.floor(Math.random() * titles.length)];
  const body = messages[Math.floor(Math.random() * messages.length)];

  return self.registration.showNotification(title, {
    body: body,
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    tag: 'moment-of-peace',
    renotify: true,
    data: {
      channelId: 'cc-radio-notifications'
    }
  });
}

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        let client = clientList[0];
        for (let i = 0; i < clientList.length; i++) {
          if (clientList[i].focused) {
            client = clientList[i];
          }
        }
        return client.focus();
      }
      return clients.openWindow('/');
    })
  );
});

// Explicit fetch listener for PWA compliance
self.addEventListener('fetch', (event) => {
  // Workbox handles routing, but Chrome requires this listener to be present
});
